feat: append junit
- Add 'junit:junit:4.12' to the implementation item of `build.gradle` file due to
  error: cannot find symbol @RunWith(SpringRunner.class)